[package]
name = "penumbra-app"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
cnidarium = { path = "../../cnidarium" }
cnidarium-component = { path = "../../cnidarium-component" }
penumbra-proto = { path = "../../proto", features = ["cnidarium"] }
penumbra-tct = { path = "../../crypto/tct" }
penumbra-proof-params = { path = "../../crypto/proof-params" }
penumbra-asset = { path = "../asset" }
penumbra-keys = { path = "../keys" }
penumbra-num = { path = "../num" }
penumbra-chain = { path = "../component/chain", features = ["component"] }
penumbra-shielded-pool = { path = "../component/shielded-pool", features = [
    "component",
] }
penumbra-stake = { path = "../component/stake" }
penumbra-governance = { path = "../component/governance" }
penumbra-sct = { path = "../component/sct" }
penumbra-fee = { path = "../component/fee" }
penumbra-dao = { path = "../component/dao" }
penumbra-dex = { path = "../component/dex" }
penumbra-ibc = { path = "../component/ibc", features = ["component"] }
penumbra-distributions = { path = "../component/distributions" }
penumbra-compact-block = { path = "../component/compact-block" }
penumbra-transaction = { path = "../transaction", features = ["parallel"] }
wrapper-derive = { path = "../../util/wrapper-derive" }

# Penumbra dependencies
decaf377 = { version = "0.5" }
decaf377-rdsa = { version = "0.7" }
jmt = "0.9"
tokio = { version = "1.21.1", features = ["full", "tracing"] }
async-trait = "0.1.52"
tonic = "0.10"
futures = "0.3"
anyhow = "1"
tracing = "0.1"
ark-ff = { version = "0.4", default_features = false }
blake2b_simd = "0.5"
bincode = "1.3.3"
serde = { version = "1", features = ["derive"] }
serde_with = "2.2"
metrics = "0.19.0"
sha2 = "0.9"
serde_json = "1"
serde_unit_struct = "0.1"
bech32 = "0.8"
im = "15.1.0"
regex = "1.5"
once_cell = "1.8"
bitvec = "1"
hex = "0.4"
base64 = "0.20"
tempfile = "3.3.0"
prost = "0.12.3"
rand_chacha = "0.3"
parking_lot = "0.12"

tendermint = "0.34.0"
tendermint-proto = "0.34.0"
tendermint-light-client-verifier = "0.34.0"
ibc-types = { version = "0.10.0", default-features = false }
ibc-proto = { version = "0.39.0", default-features = false, features = [
    "server",
] }

[dev-dependencies]
ed25519-consensus = "2"
rand_core = "0.6"
rand_chacha = "0.3"
tracing-subscriber = "0.3"

[features]
default = ["std"]
std = ["ark-ff/std", "ibc-types/std"]
