[package]
name        = "penumbra-app"
version     = { workspace = true }
authors     = { workspace = true }
edition     = { workspace = true}
repository  = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
publish     = false

[features]
default = ["std"]
std     = ["ark-ff/std", "ibc-types/std"]

[dependencies]
anyhow                           = { workspace = true }
ark-ff                           = { workspace = true, default-features = false }
async-trait                      = { workspace = true }
base64                           = { workspace = true }
bech32                           = { workspace = true }
bincode                          = { workspace = true }
bitvec                           = { workspace = true }
blake2b_simd                     = { workspace = true }
cnidarium                        = { workspace = true, features = ["migration", "rpc"], default-features = true }
cnidarium-component              = { workspace = true, default-features = true }
decaf377                         = { workspace = true, default-features = true }
decaf377-rdsa                    = { workspace = true }
futures                          = { workspace = true }
hex                              = { workspace = true }
ibc-proto                        = { workspace = true, default-features = false, features = ["server"] }
ibc-types                        = { workspace = true, default-features = false }
ics23                            = { workspace = true }
im                               = { workspace = true }
jmt                              = { workspace = true }
metrics                          = { workspace = true }
once_cell                        = { workspace = true }
parking_lot                      = { workspace = true }
penumbra-asset                   = { workspace = true, default-features = true }
penumbra-auction                 = { workspace = true, default-features = true }
penumbra-community-pool          = { workspace = true, default-features = true }
penumbra-compact-block           = { workspace = true, default-features = true }
penumbra-dex                     = { workspace = true, default-features = true }
penumbra-distributions           = { workspace = true, default-features = true }
penumbra-fee                     = { workspace = true, default-features = true }
penumbra-funding                 = { workspace = true, default-features = true }
penumbra-governance              = { workspace = true, default-features = true }
penumbra-ibc                     = { workspace = true, features = ["component", "rpc"], default-features = true }
penumbra-keys                    = { workspace = true, default-features = true }
penumbra-num                     = { workspace = true, default-features = true }
penumbra-proof-params            = { workspace = true, default-features = true }
penumbra-proto                   = { workspace = true, features = ["cnidarium"], default-features = true }
penumbra-sct                     = { workspace = true, default-features = true }
penumbra-shielded-pool           = { workspace = true, features = ["component"], default-features = true }
penumbra-stake                   = { workspace = true, default-features = true }
penumbra-tct                     = { workspace = true, default-features = true }
penumbra-test-subscriber         = { workspace = true }
penumbra-tower-trace             = {  path = "../../util/tower-trace"  }
penumbra-transaction             = { workspace = true, features = ["parallel"], default-features = true }
penumbra-txhash                  = { workspace = true, default-features = true }
prost                            = { workspace = true }
rand_chacha                      = { workspace = true }
regex                            = { workspace = true }
serde                            = { workspace = true, features = ["derive"] }
serde_json                       = { workspace = true }
serde_unit_struct                = { workspace = true }
serde_with                       = { workspace = true }
sha2                             = { workspace = true }
tempfile                         = { workspace = true }
tendermint                       = { workspace = true }
tendermint-light-client-verifier = { workspace = true }
tendermint-proto                 = { workspace = true }
tokio                            = { workspace = true, features = ["full", "tracing"] }
tokio-util                       = { workspace = true }
tonic                            = { workspace = true }
tonic-reflection                 = { workspace = true }
tonic-web                        = { workspace = true }
tower                            = { workspace = true, features = ["full"] }
tower-abci                       = "0.15"
tower-actor                      = "0.1.0"
tower-service                    = { workspace = true }
tracing                          = { workspace = true }
url                              = { workspace = true }

[dev-dependencies]
axum-server                      = { workspace = true }
camino                           = { workspace = true }
decaf377-fmd                     = { workspace = true, default-features = true }
ed25519-consensus                = { workspace = true }
penumbra-mock-client             = { workspace = true }
penumbra-mock-consensus          = { workspace = true }
penumbra-proto                   = { workspace = true, features = ["box-grpc"] }
penumbra-test-subscriber         = { workspace = true }
penumbra-mock-tendermint-proxy   = { workspace = true }
penumbra-view                    = { workspace = true }
penumbra-wallet                  = { workspace = true }
rand                             = { workspace = true }
rand_chacha                      = { workspace = true }
rand_core                        = { workspace = true }
tap                              = { workspace = true }
tempfile                         = { workspace = true }
tendermint-config                = { workspace = true }
tower-http                       = { workspace = true }
tracing-subscriber               = { workspace = true }
url                              = { workspace = true }

# Enable the feature flags to get proving keys when running tests.
[dev-dependencies.penumbra-proof-params]
workspace = true
features = [
    "bundled-proving-keys",
    "download-proving-keys",
]
