[package]
name = "penumbra-custody"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
ark-ff = "0.4"
ark-serialize = "0.4"
blake2b_simd = "0.5"
chacha20poly1305 = "0.9"
decaf377 = "0.5"
decaf377-rdsa = "0.7"
decaf377-frost = { path = "../crypto/decaf377-frost" }
decaf377-ka = { path = "../crypto/decaf377-ka" }
penumbra-chain = { path = "../core/component/chain" }
penumbra-keys = { path = "../core/keys" }
penumbra-txhash = { path = "../core/txhash" }
penumbra-proto = { path = "../proto", features = ["rpc"] }
penumbra-transaction = { path = "../core/transaction" }

tokio = { version = "1.21.1", features = ["full"] }
anyhow = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "2.2", features = ["hex"] }
tracing = "0.1"
tonic = "0.10"
bytes = { version = "1", features = ["serde"] }
prost = "0.12.3"
futures = "0.3"
hex = "0.4"
rand_core = "0.6"
ed25519-consensus = "2.1"
base64 = "0.20"

[dev-dependencies]
toml = "0.5"
