[package]
name = "penumbra-governance"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-chain/component",
    "penumbra-sct/component",
    "penumbra-stake/component",
    "tokio",
    "tonic",
]
# proving-keys = ["penumbra-proof-params/proving-keys"]
default = ["std", "component"]
std = ["ark-ff/std", "ibc-types/std"]
parallel = [
    "penumbra-tct/parallel",
    "ark-ff/parallel",
    "decaf377-rdsa/parallel",
    "ark-groth16/parallel",
    "ark-r1cs-std/parallel",
    "decaf377/parallel",
]
docsrs = []

[dependencies]
# Workspace dependencies
cnidarium = { path = "../../../cnidarium", optional = true }
cnidarium-component = { path = "../../../cnidarium-component", optional = true }
penumbra-proto = { path = "../../../proto", default-features = false }
penumbra-tct = { path = "../../../crypto/tct" }
penumbra-proof-params = { path = "../../../crypto/proof-params", default-features = false }
penumbra-sct = { path = "../sct", default-features = false }
penumbra-shielded-pool = { path = "../shielded-pool", default-features = false }
penumbra-stake = { path = "../stake", default-features = false }
penumbra-community-pool = { path = "../community-pool", default-features = false }
penumbra-fee = { path = "../fee", default-features = false }
penumbra-ibc = { path = "../ibc", default-features = false }
penumbra-distributions = { path = "../distributions", default-features = false }
penumbra-chain = { path = "../chain", default-features = false }
penumbra-asset = { path = "../../../core/asset", default-features = false }
penumbra-keys = { path = "../../../core/keys", default-features = false }
penumbra-txhash = { path = "../../../core/txhash", default-features = false }
penumbra-num = { path = "../../../core/num", default-features = false }

# Penumbra dependencies
decaf377-rdsa = { version = "0.7" }
decaf377 = { version = "0.5", features = ["r1cs"] }

# Crates.io dependencies
base64 = "0.21"
ark-r1cs-std = { version = "0.4", default-features = false }
ark-relations = "0.4"
ark-ff = { version = "0.4", default_features = false }
ark-serialize = "0.4"
ark-groth16 = { version = "0.4", default-features = false }
ark-snark = "0.4"
async-stream = "0.2"
metrics = "0.19.0"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
anyhow = "1"
async-trait = "0.1.52"
tendermint = "0.34.0"
blake2b_simd = "0.5"
bytes = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
im = "15.1"
regex = "1.5"
futures = "0.3"
pbjson-types = "0.6"
once_cell = "1.8"
rand_chacha = "0.3"
ibc-types = { version = "0.11.0", default-features = false }

# Component dependencies
tokio = { version = "1.21.1", features = ["full", "tracing"], optional = true }
tonic = { version = "0.10", optional = true }


[dev-dependencies]
proptest = "1"
proptest-derive = "0.3"
