[package]
name = "penumbra-compact-block"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-chain/component",
    "tonic",
    "tokio-stream",
    "tokio",
]
# proving-keys = ["penumbra-proof-params/proving-keys"]
default = ["std", "component"]
std = ["ark-ff/std"]
docsrs = []

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../../proto", default-features = false }
cnidarium = { path = "../../../cnidarium", optional = true }
penumbra-tct = { path = "../../../crypto/tct" }
penumbra-proof-params = { path = "../../../crypto/proof-params", default-features = false }
cnidarium-component = { path = "../../../cnidarium-component", optional = true }
penumbra-chain = { path = "../chain", default-features = false }
penumbra-shielded-pool = { path = "../shielded-pool", default-features = false }
penumbra-dex = { path = "../dex", default-features = false }
penumbra-ibc = { path = "../ibc", default-features = false }
penumbra-community-pool = { path = "../community-pool", default-features = false }
penumbra-governance = { path = "../governance", default-features = false }
penumbra-stake = { path = "../stake", default-features = false }
penumbra-fee = { path = "../fee", default-features = false }
penumbra-sct = { path = "../sct", default-features = false }

# Crates.io dependencies
ark-ff = { version = "0.4", default_features = false }
decaf377-rdsa = { version = "0.7" }
metrics = "0.19.0"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
anyhow = "1"
async-trait = "0.1.52"
tendermint = "0.34.0"
blake2b_simd = "0.5"
bytes = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
futures = "0.3.28"
tonic = { version = "0.10", optional = true }
tokio-stream = { version = "0.1", optional = true }
tokio = { version = "1", optional = true }
im = "15.1.0"
