[package]
name = "penumbra-shielded-pool"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-ibc/component",
    "penumbra-chain/component",
    "penumbra-sct/component",
    "tonic",
]
# proving-keys = ["penumbra-proof-params/proving-keys"]
default = ["std", "component"]
std = ["ark-ff/std"]
parallel = [
    "penumbra-tct/parallel",
    "ark-ff/parallel",
    "poseidon377/parallel",
    "decaf377-rdsa/parallel",
    "ark-groth16/parallel",
    "ark-r1cs-std/parallel",
    "decaf377/parallel",
    "tonic",
]
docsrs = []

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../../proto", default-features = false }
cnidarium = { path = "../../../cnidarium", optional = true }
penumbra-tct = { path = "../../../crypto/tct" }
penumbra-proof-params = { path = "../../../crypto/proof-params", default-features = false }
penumbra-sct = { path = "../sct", default-features = false }
cnidarium-component = { path = "../../../cnidarium-component", optional = true }
penumbra-ibc = { path = "../ibc", default-features = false }
penumbra-chain = { path = "../chain", default-features = false }
penumbra-asset = { path = "../../../core/asset", default-features = false }
penumbra-num = { path = "../../../core/num", default-features = false }
penumbra-keys = { path = "../../../core/keys", default-features = false }
penumbra-txhash = { path = "../../../core/txhash", default-features = false }
decaf377-ka = { path = "../../../crypto/decaf377-ka/" }
decaf377-fmd = { path = "../../../crypto/decaf377-fmd/" }

# Penumbra dependencies
ibc-types = { version = "0.11.0", default-features = false }
decaf377-rdsa = { version = "0.7" }
decaf377 = { version = "0.5", features = ["r1cs"] }
poseidon377 = { version = "0.6", features = ["r1cs"] }

# Crates.io dependencies
base64 = "0.20"
thiserror = "1"
chacha20poly1305 = "0.9.0"
ark-r1cs-std = { version = "0.4", default-features = false }
ark-relations = "0.4"
ark-ff = { version = "0.4", default_features = false }
ark-serialize = "0.4"
ark-groth16 = { version = "0.4", default-features = false }
ark-snark = "0.4"
metrics = "0.19.0"
prost = "0.12.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
anyhow = "1"
async-trait = "0.1.52"
tendermint = "0.34.0"
blake2b_simd = "0.5"
bytes = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
im = "15.1"
once_cell = "1.8"
hex = "0.4"

# Component dependencies
tonic = { version = "0.10", optional = true }

[dev-dependencies]
proptest = "1"
