[package]
name = "penumbra-proto"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decaf377-fmd = { path = "../crypto/decaf377-fmd" }
decaf377-rdsa = { version = "0.7" }
bytes = { version = "1", features = ["serde"] }
prost = "0.12.3"
tonic = { version = "0.10", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
anyhow = "1.0"
subtle-encoding = "0.5"
bech32 = "0.8"
cnidarium = { path = "../cnidarium", optional = true }
ibc-types = { version = "0.11.0", features = ["std"] }
pin-project = "1"
async-trait = "0.1.52"
async-stream = "0.2.0"
tracing = "0.1"
futures = "0.3"
pbjson = "0.6"
pbjson-types = "0.6"

ibc-proto = { version = "0.40.0", default-features = false, features = [
    "std",
    "serde",
] }

ics23 = "0.11.0"
tendermint = "0.34.0"

[build-dependencies]
anyhow = "1"

[features]
rpc = ["dep:tonic", "ibc-proto/client"]
cnidarium = ["dep:cnidarium"]
