[package]
name = "penumbra-view"
version = "0.64.1"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The view RPC library for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
# When this feature is enabled, the view worker will request every single
# SCT root, to pinpoint exactly where any SCT root divergence occurs.
sct-divergence-check = []
std = ["ark-std/std"]

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto", features = ["rpc"] }
penumbra-tct = { path = "../crypto/tct" }
penumbra-num = { path = "../core/num" }
penumbra-keys = { path = "../core/keys" }
penumbra-asset = { path = "../core/asset" }
penumbra-chain = { path = "../core/component/chain" }
penumbra-shielded-pool = { path = "../core/component/shielded-pool", default-features = false }
penumbra-governance = { path = "../core/component/governance", default-features = false }
penumbra-stake = { path = "../core/component/stake", default-features = false }
penumbra-ibc = { path = "../core/component/ibc", default-features = false }
penumbra-distributions = { path = "../core/component/distributions", default-features = false }
penumbra-community-pool = { path = "../core/component/community-pool", default-features = false }
penumbra-dex = { path = "../core/component/dex", default-features = false }
penumbra-sct = { path = "../core/component/sct", default-features = false }
penumbra-fee = { path = "../core/component/fee", default-features = false }
penumbra-compact-block = { path = "../core/component/compact-block", default-features = false }
penumbra-app = { path = "../core/app" }
penumbra-transaction = { path = "../core/transaction" }

ibc-types = { version = "0.11.0", default-features = false }

ark-std = { version = "0.4", default-features = false }
decaf377 = { version = "0.5", features = ["r1cs"] }
tokio = { version = "1.22", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["sync"] }
anyhow = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tonic = "0.10"
url = "2"
bytes = { version = "1", features = ["serde"] }
prost = "0.12.3"
futures = "0.3"
hex = "0.4"
metrics = "0.19.0"
async-stream = "0.2"
parking_lot = "0.12"
clap = { version = "3", features = ["derive"] }
camino = "1"
async-trait = "0.1"
tendermint = "0.34.0"
sha2 = "0.10.1"
ed25519-consensus = "2.1"
r2d2 = "0.8"
# Depending on our fork of r2d2-sqlite, which updates the rusqlite dependency to 0.29
r2d2_sqlite = { version = "0.22", git = "https://github.com/penumbra-zone/r2d2-sqlite.git", features = [
    "bundled",
] }
genawaiter = "0.99"
digest = "0.9"
once_cell = "1"
