[package]
name = "penumbra-proof-setup"
version = "0.64.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
ark-ec = { version = "0.4.2", default_features = false }
ark-ff = { version = "0.4.2", default_features = false }
ark-groth16 = { version = "0.4.0", default_features = false }
ark-poly = { version = "0.4.2", default_features = false }
ark-relations = "0.4"
ark-serialize = "0.4.2"
blake2b_simd = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
decaf377 = { version = "0.5", default_features = false }
penumbra-dex = { path = "../../core/component/dex/" }
penumbra-community-pool = { path = "../../core/component/community-pool/", features = [
    "component",
] }
penumbra-governance = { path = "../../core/component/governance/" }
penumbra-proof-params = { path = "../proof-params" }
penumbra-proto = { path = "../../proto" }
penumbra-shielded-pool = { path = "../../core/component/shielded-pool/" }
penumbra-stake = { path = "../../core/component/stake/", features = [
    "component",
] }
rayon = { version = "1.8.0", optional = true }

[dev-dependencies]
ark-r1cs-std = "0.4.0"
ark-snark = "0.4.0"
criterion = { version = "0.4", features = ["html_reports"] }
penumbra-dex = { path = "../../core/component/dex/" }
penumbra-proof-params = { path = "../proof-params" }
rand_chacha = "0.3.1"

[[bench]]
name = "all"
harness = false

[features]
default = []
parallel = [
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-groth16/parallel",
    "decaf377/parallel",
    "rayon",
    "penumbra-shielded-pool/parallel",
]
