[package]
name = "pcli"
version = "0.64.1"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The command-line interface for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "parallel", "download-proving-keys"]
download-proving-keys = ["penumbra-proof-params/download-proving-keys"]
sct-divergence-check = ["penumbra-view/sct-divergence-check"]
std = ["ark-ff/std", "ibc-types/std"]
parallel = [
    "penumbra-proof-params/parallel",
    "decaf377/parallel",
    "penumbra-shielded-pool/parallel",
    "penumbra-dex/parallel",
    "penumbra-governance/parallel",
    "penumbra-stake/parallel",
    "penumbra-transaction/parallel",
    "penumbra-wallet/parallel",
    "penumbra-proof-setup/parallel",
]

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../proto", features = ["rpc"] }
penumbra-tct = { path = "../../crypto/tct" }
penumbra-num = { path = "../../core/num", default-features = false }
penumbra-asset = { path = "../../core/asset", default-features = false }
penumbra-keys = { path = "../../core/keys", default-features = false }
penumbra-chain = { path = "../../core/component/chain", default-features = false }
penumbra-shielded-pool = { path = "../../core/component/shielded-pool", default-features = false }
penumbra-governance = { path = "../../core/component/governance", default-features = false }
penumbra-stake = { path = "../../core/component/stake", default-features = false }
penumbra-sct = { path = "../../core/component/sct", default-features = false }
penumbra-fee = { path = "../../core/component/fee", default-features = false }
penumbra-dex = { path = "../../core/component/dex", default-features = false }
penumbra-community-pool = { path = "../../core/component/community-pool", default-features = false }
penumbra-ibc = { path = "../../core/component/ibc", default-features = false }
penumbra-compact-block = { path = "../../core/component/compact-block", default-features = false }
penumbra-transaction = { path = "../../core/transaction", features = ["clap"] }
penumbra-proof-setup = { path = "../../crypto/proof-setup" }
penumbra-app = { path = "../../core/app" }
penumbra-wallet = { path = "../../wallet" }
penumbra-custody = { path = "../../custody" }
penumbra-view = { path = "../../view" }

# Penumbra dependencies
decaf377 = { version = "0.5" }
decaf377-rdsa = { version = "0.7" }
tendermint = { version = "0.34.0", features = ["rust-crypto"] }
jmt = "0.9"

# External dependencies
ibc-types = { version = "0.11.0", features = ["std", "with_serde"] }

ibc-proto = { version = "0.40.0" }
ark-ff = { version = "0.4", default-features = false }
atty = "0.2"
ed25519-consensus = "2"
futures = "0.3"
async-stream = "0.2"
bincode = "1.3.3"
blake2b_simd = "0.5"
base64 = "0.21"
simple-base64 = "0.23"
bytes = "1"
comfy-table = "5"
directories = "4.0.1"
tokio = { version = "1.22", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7"
tower = { version = "0.4", features = ["full"] }
tracing = "0.1"
tonic = { version = "0.10", features = ["tls-webpki-roots", "tls"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "ansi"] }
pin-project = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
regex = "1.6.0"
serde_with = { version = "1.11", features = ["hex"] }
sha2 = "0.9"
anyhow = "1"
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3.1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rpassword = "7"
indicatif = "0.16"
http-body = "0.4.5"
clap = { version = "3", features = ["derive", "env"] }
camino = "1"
url = { version = "2", features = ["serde"] }
colored_json = "2.1"
toml = { version = "0.7", features = ["preserve_order"] }
walkdir = "2"
once_cell = "1"
ndarray = "0.15.6"
dialoguer = "0.10.4"
# ndarray-linalg = { version = "0.16.0", features = ["openblas-static"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
tempfile = "3.3.0"
regex = "1.6.0"
penumbra-governance = { path = "../../core/component/governance", default-features = false }
penumbra-proof-params = { path = "../../crypto/proof-params", features = [
    "bundled-proving-keys",
    "download-proving-keys",
] }

[package.metadata.dist]
dist = true
