[package]
name = "pclientd"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "download-proving-keys"]
std = ["ibc-types/std"]
sct-divergence-check = ["penumbra-view/sct-divergence-check"]
# Enable to use rayon parallelism for crypto operations
parallel = ["penumbra-transaction/parallel"]
download-proving-keys = ["penumbra-proof-params/download-proving-keys"]

[dependencies]
# Workspace dependencies
penumbra-proto            = { path = "../../proto", features = ["rpc"] }
penumbra-tct              = { path = "../../crypto/tct" }
penumbra-asset           = { path = "../../core/asset" }
penumbra-keys           = { path = "../../core/keys" }
penumbra-chain            = { path = "../../core/component/chain" }
penumbra-transaction      = { path = "../../core/transaction" }
penumbra-app              = { path = "../../core/app" }
penumbra-custody          = { path = "../../custody" }
penumbra-view             = { path = "../../view" }

tokio = { version = "1.22", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["sync"] }
anyhow = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", features = ["hex"] }
tracing = "0.1"
tracing-subscriber = "0.2"
url = { version = "2", features = ["serde"] }
http = "0.2.9"
http-body = "0.4.5"
tower = "0.4.0"
tonic = "0.10"
tonic-web = "0.10.0"
tonic-reflection = "0.10.0"
bytes = { version = "1", features = ["serde"] }
prost = "0.12.3"
futures = "0.3"
hex = "0.4"
metrics = "0.19.0"
async-stream = "0.2"
parking_lot = "0.12"
clap = { version = "3", features = ["derive", "env"] }
camino = "1"
async-trait = "0.1"
tendermint = "0.34.0"
sha2 = "0.10.1"
toml = "0.5"
ed25519-consensus = "2.1"
atty = "0.2"
directories = "4.0.1"

[dev-dependencies]
tempfile = "3.3.0"
assert_cmd = "2.0"
base64 = "0.20"
ibc-types = { version = "0.11.0" }
ibc-proto = { version = "0.40.0", default-features = false, features = ["server"] }
penumbra-proof-params = { path = "../../crypto/proof-params", features = [
    "bundled-proving-keys",
    "download-proving-keys",
] }
